### ISSUE TITLE
Seed idea does not bring across the resources directory

### ISSUE THREAD

**Issue by PhilAndrew** [tindzk/seed#103]
```
[module.what.jvm]
...
resources = ["jvm/resources"]

```

After running seed idea, then opening it in IntelliJ I would like the resources to be on the classpath. The module in IntelliJ should have the resources directory set. Then if I want to run from IntelliJ it will pickup the resources directory.

What I do now to work-around this problem is that I open the project in IntelliJ and go to the module and set the resources directory in the UI. I do this as I like to run from IntelliJ using the debugger.

Also seed run seems to not take into the resources directory.

` seed run mymodule:jvm`

**Comment by tindzk** [comment]
Thanks. I could reproduce the IDEA issue and have a fix in the pipeline. However, `seed run` works fine on my example project in the linked pull request.
