### ISSUE TITLE
JVM resources are not copied into jar

### ISSUE THREAD

**Issue by hohonuuli** [tindzk/seed#106]
__tl;dr__

Files in the resource directory are not being copied into the built jar file. 

__the sordid details__

I've set up a project that mimics a sbt/maven layout (src/main/scala, src/main/resources, etc). The source for the project is at <https://github.com/hohonuuli/demoseed>. In this project there is a resource file at `src/main/resources/logback.xml`.  My module is configured like so:

```
[module.demoseed.jvm]
root = "."
resources = [
  "src/main/resources"
]
sources = [
  "src/main/scala",
  "src/main/java"
]
scalaDeps = [
  ["io.circe", "circe-core", "0.13.0"]
]
```

I ran the following:

```
seed all
seed package demoseed --libs
```

Everything compiles just fine, but I can't find the logback.xml file from resources in the built jar. e.g. 

```
❯ jar -tvf build/dist/demoseed.jar
   702 Mon Jun 22 17:39:16 PDT 2020 META-INF/MANIFEST.MF
     0 Mon Jun 22 17:39:14 PDT 2020 demoseed/
   925 Mon Jun 22 17:39:14 PDT 2020 demoseed/Main$.class
   301 Mon Jun 22 17:39:14 PDT 2020 demoseed/Foo.class
   635 Mon Jun 22 17:39:14 PDT 2020 demoseed/Main.class
```

At this point, I can't tell if this is a bug in seed or if I've missed some configuration. Any help is appreciated. (BTW, seed is pretty cool!)

**Comment by tindzk** [comment]
Thanks for the detailed bug report! I agree that `package` should copy resource files too. #108 will fix this.
