### ISSUE TITLE
Line numbers of compilation errors are off by one

### ISSUE THREAD

**Issue by nafg** [tindzk/seed#70]
Maybe they are zero-based?

**Comment by tindzk** [comment]
Do you have an example? I created the following file:

```toml
[project
```

The error output indicated the correct line number:

```bash
$ seed update
ⓘ Loading project build.toml...
✗ The build file build.toml is malformed
  Message: End:1:1 ..."[project\n"
```

**Comment by nafg** [comment]
Sorry, I meant sources' compile errors, like in a scala file.

**Comment by tindzk** [comment]
Indeed, good catch! I have a PR in the pipeline.
