### ISSUE TITLE
Question: How to specify compiler version in scalaDeps?

### ISSUE THREAD

**Issue by PhilAndrew** [tindzk/seed#81]
I tried the following but it didn't work.

scalaDeps = [["org.wvlet.airframe", "airframe", "20.2.1", "2.12"]]

```
➜  ideal git:(master) ✗ ./seed bloop
ⓘ Loading project build.toml...
✗ The build file build.toml is malformed
  Message: Invalid version tag provided
  Trace: module → ideal → scalaDeps → #1 → #4
➜  ideal git:(master) ✗
```

**Comment by tindzk** [comment]
The Scala version does not need to be specified. It is derived from `scalaVersion` and added to the package name. The fourth parameter of a `scalaDeps` item denotes its version tag. This is useful when a Scala package does not follow the convention of `<name>_<majorVersion>.<minorVersion>`. You can find more information [here](https://github.com/tindzk/seed#dependencies).

**Comment by tindzk** [comment]
Did it resolve your issue?
